# Generated by Django 5.2 on 2025-04-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='data_coleta',
        ),
        migrations.RemoveField(
            model_name='item',
            name='especime',
        ),
    ]
