# Generated by Django 5.2 on 2025-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0002_remove_item_data_coleta_remove_item_especime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='descricao',
        ),
        migrations.AddField(
            model_name='item',
            name='data_coleta',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='item',
            name='especime',
            field=models.CharField(default='desconhecido', max_length=100),
        ),
    ]
